#!/usr/bin/env python3
"""Fix <text> clipping in SVG files generated by R/ggplot2/svglite.

rsvg-convert and Word's SVG renderer don't fully support textLength/lengthAdjust
attributes. Text with text-anchor='middle' + textLength renders at its natural
width (wider than intended), causing overflow beyond clip-path boundaries.

This script:
1. Moves <text> from narrow clip-path groups to the full canvas clip-path group
2. For moved text only: converts text-anchor='middle'/'end' to 'start' with x
   recalculated to the intended left edge, removing textLength/lengthAdjust
   (Axis labels and titles in the full canvas group are NOT modified.)

The operation is idempotent.

Usage:
    python3 fix-svg-clips.py src/figs/f4_v2_fig.svg
    python3 fix-svg-clips.py src/figs/*.svg
"""

import re
import sys


def _transform_text(line):
    """Convert text-anchor/textLength to start-anchored at intended left edge.

    For text-anchor='middle': new_x = x - textLength/2
    For text-anchor='end':    new_x = x - textLength
    Removes textLength and lengthAdjust attributes.
    Skips text with transform= (e.g. rotated axis titles).
    Returns (transformed_line, was_changed).
    """
    s = line.strip()

    # Skip text with transform attribute (rotated labels etc.)
    if "transform=" in s:
        return line, False

    tl_match = re.search(r"textLength='([^']+)'", s)
    if not tl_match:
        return line, False

    anchor_match = re.search(r"text-anchor='([^']+)'", s)
    anchor = anchor_match.group(1) if anchor_match else "start"

    if anchor == "start":
        return line, False

    x_match = re.search(r"\bx='([^']+)'", s)
    if not x_match:
        return line, False

    x = float(x_match.group(1))
    text_length = float(tl_match.group(1).replace("px", ""))

    # Calculate start position
    if anchor == "middle":
        new_x = x - text_length / 2
    elif anchor == "end":
        new_x = x - text_length
    else:
        return line, False

    # Apply changes to the line
    new_line = line
    new_line = re.sub(r"\bx='[^']+'", f"x='{new_x:.2f}'", new_line)
    new_line = re.sub(r"text-anchor='[^']+'", "text-anchor='start'", new_line)
    new_line = re.sub(r"\s*textLength='[^']+'", "", new_line)
    new_line = re.sub(r"\s*lengthAdjust='[^']+'", "", new_line)

    return new_line, True


def fix_svg_clips(path):
    """Fix text clipping in an SVG file.

    Returns the number of text elements fixed (0 if no changes needed).
    """
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    text = "".join(lines)

    # Parse viewBox dimensions
    m = re.search(r"viewBox=['\"]([^'\"]+)['\"]", text)
    if not m:
        return 0
    vb = [float(x) for x in m.group(1).split()]
    vb_w, vb_h = vb[2], vb[3]

    # Parse clipPath definitions: id → (x, y, width, height)
    clips = {}
    for m in re.finditer(
        r"<clipPath\s+id=['\"]([^'\"]+)['\"]>\s*"
        r"<rect\s+x=['\"]([^'\"]+)['\"]\s+y=['\"]([^'\"]+)['\"]\s+"
        r"width=['\"]([^'\"]+)['\"]\s+height=['\"]([^'\"]+)['\"]",
        text,
    ):
        clips[m.group(1)] = tuple(float(m.group(i)) for i in range(2, 6))

    if not clips:
        return 0

    # Classify: full canvas vs narrow clip-paths
    full_ids = {
        cid
        for cid, (x, y, w, h) in clips.items()
        if abs(w - vb_w) < 1 and abs(h - vb_h) < 1
    }
    narrow_ids = set(clips) - full_ids

    if not narrow_ids:
        return 0

    # Walk lines tracking clip-path group nesting via a stack
    result = []
    stack = []  # [(clip_id or None, is_narrow)]
    extracted = []
    last_full_close_idx = None

    for line in lines:
        s = line.strip()

        # Opening <g ...>
        if re.match(r"<g[\s>]", s) or s == "<g>":
            gm = re.search(r"clip-path=['\"]url\(#([^)]+)\)['\"]", s)
            if gm:
                cid = gm.group(1)
                stack.append((cid, cid in narrow_ids))
            else:
                stack.append((None, False))
            result.append(line)
            continue

        # Closing </g>
        if s == "</g>":
            if stack:
                cid, _ = stack.pop()
                if cid in full_ids:
                    last_full_close_idx = len(result)
            result.append(line)
            continue

        # If inside any narrow clip-path group, extract <text> elements
        in_narrow = any(is_n for _, is_n in stack)
        if in_narrow and s.startswith("<text"):
            # Move + transform: recalculate position for renderers that
            # don't support textLength/lengthAdjust
            new_line, _ = _transform_text(line)
            extracted.append(new_line)
            continue

        result.append(line)

    if not extracted:
        return 0

    # Insert extracted texts into the last full-canvas group (before its </g>)
    if last_full_close_idx is not None:
        for tl in reversed(extracted):
            result.insert(last_full_close_idx, tl)
    else:
        for i in range(len(result) - 1, -1, -1):
            if result[i].strip() == "</g>":
                for tl in reversed(extracted):
                    result.insert(i, tl)
                break

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(result)

    return len(extracted)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <svg> [<svg> ...]", file=sys.stderr)
        sys.exit(1)

    total = 0
    for p in sys.argv[1:]:
        n = fix_svg_clips(p)
        if n:
            print(f"  {p}: fixed {n} text element(s)")
            total += n

    if total:
        print(f"Fixed {total} text element(s) total")


if __name__ == "__main__":
    main()
